spring.application.name=SplitWise

spring.datasource.url=jdbc:postgresql://localhost:5432/splitwise
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.cloud.task.initialize-enabled=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql

spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.datasource.init=DEBUG