spring.application.name=SplitWise


#PGHOST: postgres.railway.internal
#PGPORT: 5432
#PGDATABASE: railway
#PGUSER: postgres
#PGPASSWORD: JTRceYxwTabFSokmwPqzGrezezIUjimD

# =========================
# DATABASE CONFIG (RAILWAY + LOCAL COMPATIBLE)
# =========================

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:splitwise}}
#postgresql://postgres:JTRceYxwTabFSokmwPqzGrezezIUjimD@postgres.railway.internal:5432/railway
spring.datasource.username=${PGUSER:${POSTGRES_USER:postgres}}

spring.datasource.password=${PGPASSWORD:${POSTGRES_PASSWORD:password}}

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA CONFIG
# =========================

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.defer-datasource-initialization=true

# =========================
# SQL INIT (for schema.sql)
# =========================

spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.sql.init.schema-locations=classpath:db/schema.sql

# =========================
# CLOUD TASK (disable if not needed)
# =========================

spring.cloud.task.initialize-enabled=false

# =========================
# LOGGING
# =========================

logging.level.org.springframework.jdbc.datasource.init=${JDBC_LOG_LEVEL:DEBUG}